apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: default
      nodeName: cpu-04
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: chenjinyuan/opentelemetry:currency-delphinus
        ports:
        - name: grpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otelcollector:4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=currencyservice,service.version=1.0.0"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
