apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: default
      nodeName: cpu-04
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: chenjinyuan/opentelemetry:payment
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: MONGO_URI
          value: mongodb-paymentservice:27017
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otelcollector:4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=paymentservice,service.version=1.0.0"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
