apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  replicas: 4
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      serviceAccountName: default
      nodeName: cpu-08
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: chenjinyuan/opentelemetry:productcatalog-delphinus
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: MONGO_URI
          value: mongodb-productcatalogservice:27017
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otelcollector:4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=productcatalogservice,service.version=1.0.0"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
