apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: default
      nodeName: cpu-06
      containers:
      - name: server
        image: chenjinyuan/opentelemetry:shipping
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otelcollector:4317"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=shippingservice,service.version=1.0.0"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
