# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distributed.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64istributed.proto\x12\x0b\x64istributed\")\n\nResRequest\x12\x0c\n\x04uids\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"\x1d\n\x0bResResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x97\x01\n\x0bGrpcService\x12\x43\n\x0c\x61\x64justResCPU\x12\x17.distributed.ResRequest\x1a\x18.distributed.ResResponse\"\x00\x12\x43\n\x0c\x61\x64justResMEM\x12\x17.distributed.ResRequest\x1a\x18.distributed.ResResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'distributed_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESREQUEST']._serialized_start=34
  _globals['_RESREQUEST']._serialized_end=75
  _globals['_RESRESPONSE']._serialized_start=77
  _globals['_RESRESPONSE']._serialized_end=106
  _globals['_GRPCSERVICE']._serialized_start=109
  _globals['_GRPCSERVICE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
