# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import distributed_pb2 as distributed__pb2


class GrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.adjustResCPU = channel.unary_unary(
                '/distributed.GrpcService/adjustResCPU',
                request_serializer=distributed__pb2.ResRequest.SerializeToString,
                response_deserializer=distributed__pb2.ResResponse.FromString,
                )
        self.adjustResMEM = channel.unary_unary(
                '/distributed.GrpcService/adjustResMEM',
                request_serializer=distributed__pb2.ResRequest.SerializeToString,
                response_deserializer=distributed__pb2.ResResponse.FromString,
                )


class GrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def adjustResCPU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def adjustResMEM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'adjustResCPU': grpc.unary_unary_rpc_method_handler(
                    servicer.adjustResCPU,
                    request_deserializer=distributed__pb2.ResRequest.FromString,
                    response_serializer=distributed__pb2.ResResponse.SerializeToString,
            ),
            'adjustResMEM': grpc.unary_unary_rpc_method_handler(
                    servicer.adjustResMEM,
                    request_deserializer=distributed__pb2.ResRequest.FromString,
                    response_serializer=distributed__pb2.ResResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.GrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def adjustResCPU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed.GrpcService/adjustResCPU',
            distributed__pb2.ResRequest.SerializeToString,
            distributed__pb2.ResResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def adjustResMEM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/distributed.GrpcService/adjustResMEM',
            distributed__pb2.ResRequest.SerializeToString,
            distributed__pb2.ResResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
